### ISSUE TITLE
Can't get past prompt for target Pokémon

### ISSUE THREAD

**Issue by Kevin-Escobedo** [adamsb0303/Pokemon-Shiny-Tracker#3]
I believe it's an issue with line 59 of Pokemon Shiny Tracker.cpp.
For whatever reason, selectedPokemon.generatePokemonData(pokemonName); doesn't update the generation properly and I'm stuck in an infinite loop entering Pokémon names.

**Comment by adamsb0303** [comment]
What pokemon are you entering? There may be an issue with the file

**Comment by Kevin-Escobedo** [comment]
I tried entering the starters from every gen and couldn't get past it. It only seemed to work when I tried with the Alolan variant of a Pokémon. If I tried with a Galarian variant, it just asked me twice if I was hunting the Galarian variant and then brought me back to the target Pokémon prompt.

**Comment by adamsb0303** [comment]
the only starter that I couldn't get to work was bulbasaur, and I fixed that galarian issue by moving the second getchar. Please try again with the newest commit

**Comment by Kevin-Escobedo** [comment]
Galarian forms work well now, but other Pokémon leave me in an infinite loop at the name prompt. I'm using Ubuntu 20.04 and compiling with g++, if that matters at all.

**Comment by adamsb0303** [comment]
Does the spell check work? If not there may be an issue with how linux handles the text files. I am working on Visual Studio on a Windows 10 machine, so its likely that there are some incompatibilities

**Comment by Kevin-Escobedo** [comment]
Oh, I see; I'll try running in on Windows then and let you know in a bit
