### ISSUE TITLE
Can't enter Porygon-Z as a target

### ISSUE THREAD

**Issue by Kevin-Escobedo** [adamsb0303/Pokemon-Shiny-Tracker#5]
Typing Porygon-Z into the prompt for the target Pokemon won't let you advance; it just keeps asking the user for which Pokemon they'd like to hunt. I don't know how big an issue this is, since I don't think you can directly hunt Porygon-Z in any Pokemon game and for whatever reason, other Pokemon with a hyphen in their name, like Jangmo-o, work fine.

**Comment by adamsb0303** [comment]
I think its because the file for porygon-z is "porygon-Z". It seems like changing the capital Z to lower case fixes it
